src/mini_buildd/urls.py
import django.views.generic.base
import django.views.generic.detail
import django.contrib.admin
import django.contrib.auth.views
from django.conf.urls import include, url

import mini_buildd.views
import mini_buildd.models.repository

django.contrib.admin.autodiscover()

urlpatterns = [
    # mini_buildd
    url(r"^$", django.views.generic.base.RedirectView.as_view(url="/mini_buildd/", permanent=False)),
    url(r"^mini_buildd/", include([
        url(r"^$", mini_buildd.views.home),
        url(r"^log/(.+)/(.+)/(.+)/$", mini_buildd.views.log),
        url(r"^live-buildlogs/(.+\.buildlog)$", mini_buildd.views.live_buildlogs),
        url(r"^repositories/(?P<pk>.+)/$", django.views.generic.detail.DetailView.as_view(model=mini_buildd.models.repository.Repository)),
        url(r"^api$", mini_buildd.views.api),
        url(r"^accounts/profile/$", mini_buildd.views.AccountProfileView.as_view(template_name="mini_buildd/account_profile.html")),
    ])),
    # admin
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", django.contrib.admin.site.urls),
    # registration
    url(r"^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$", django.contrib.auth.views.PasswordResetConfirmView.as_view(), name="auth_password_reset_confirm"),
    url(r"^accounts/", include("registration.backends.model_activation.urls")),
    # registration: This extra line is needed for p-d-registration since some django update...
    url(r"^accounts/", include("django.contrib.auth.urls")),
]

django.conf.urls.handler400 = mini_buildd.views.error400_bad_request
django.conf.urls.handler401 = mini_buildd.views.error401_unauthorized
django.conf.urls.handler404 = mini_buildd.views.error404_not_found
django.conf.urls.handler500 = mini_buildd.views.error500_internal

src/mini_buildd/models/repository.py
import os
import copy
import contextlib
import shutil
import glob
import re
import logging

import django.db
import django.core.exceptions
import django.contrib.auth.models

import debian.debian_support

import mini_buildd.config
import mini_buildd.misc
import mini_buildd.gnupg
import mini_buildd.reprepro

import mini_buildd.models.source
import mini_buildd.models.base

from mini_buildd.models.msglog import MsgLog
LOG = logging.getLogger(__name__)


class EmailAddress(mini_buildd.models.base.Model):
    address = django.db.models.EmailField(primary_key=True, max_length=255)
    name = django.db.models.CharField(blank=True, max_length=255)

    class Meta(mini_buildd.models.base.Model.Meta):
        verbose_name_plural = "Email addresses"

    class Admin(mini_buildd.models.base.Model.Admin):
        exclude = ("extra_options",)

    def __str__(self):
        return f"{self.name} <{self.address}>"


class Suite(mini_buildd.models.base.Model):
    name = django.db.models.CharField(
        max_length=100,
        help_text="A suite to support, usually s.th. like 'experimental', 'unstable', 'testing' or 'stable'.")

    class Admin(mini_buildd.models.base.Model.Admin):
        exclude = ("extra_options",)

    def __str__(self):
        return self.name

    # Note: pylint false-positive: https://github.com/PyCQA/pylint/issues/1553
    def clean(self, *args, **kwargs):  # pylint: disable=arguments-differ
        self.mbd_validate_regex(r"^[a-z]+$", self.name, "Name")
        super().clean(*args, **kwargs)


class SuiteOption(mini_buildd.models.base.Model):
    layout = django.db.models.ForeignKey("Layout",
                                         on_delete=django.db.models.CASCADE)
    suite = django.db.models.ForeignKey("Suite",
                                        on_delete=django.db.models.CASCADE)

    uploadable = django.db.models.BooleanField(
        default=True,
        help_text="Whether this suite should accept user uploads.")

    experimental = django.db.models.BooleanField(
        default=False,
        help_text="""
Experimental suites must be uploadable and must not
migrate. Also, the packager treats failing extra QA checks (like
lintian) as non-lethal, and will install anyway.
""")

    migrates_to = django.db.models.ForeignKey(
        "self", blank=True, null=True,
        on_delete=django.db.models.CASCADE,
        help_text="Give another suite where packages may migrate to (you may need to save this 'blank' first before you see choices here).")

    build_keyring_package = django.db.models.BooleanField(
        default=False,
        help_text="Build keyring package for this suite (i.e., when the resp. Repository action is called).")

    auto_migrate_after = django.db.models.IntegerField(
        default=0,
        help_text="For future use. Automatically migrate packages after x days.")

    not_automatic = django.db.models.BooleanField(
        default=True,
        help_text="Include 'NotAutomatic' in the Release file.")

    but_automatic_upgrades = django.db.models.BooleanField(
        default=True,
        help_text="Include 'ButAutomaticUpgrades' in the Release file.")

    class Meta(mini_buildd.models.base.Model.Meta):
        unique_together = ("suite", "layout")

    def __str__(self):
        e = "*" if self.experimental else ""
        return f"{self.layout.name}: {e}{self.suite.name}{e} [{'uploadable' if self.uploadable else 'managed'}]{' => {self.migrates_to.suite.name}' if self.migrates_to else ''}"

    # Note: pylint false-positive: https://github.com/PyCQA/pylint/issues/1553
    def clean(self, *args, **kwargs):  # pylint: disable=arguments-differ
        if self.build_keyring_package and not self.uploadable:
            raise django.core.exceptions.ValidationError("You can only build keyring packages on uploadable suites!")
        if self.experimental and self.migrates_to:
            raise django.core.exceptions.ValidationError("Experimental suites may not migrate!")
        if self.experimental and not self.uploadable:
            raise django.core.exceptions.ValidationError("Experimental suites must be uploadable!")
        if self.migrates_to and self.migrates_to.layout != self.layout:
            raise django.core.exceptions.ValidationError("Migrating suites must be in the same layout (you need to save once to make new suites visible).")
        if self.migrates_to and self.migrates_to.uploadable:
            raise django.core.exceptions.ValidationError("You may not migrate to an uploadable suite.")

        super().clean(*args, **kwargs)

    @property
    def rollback(self):
        """Rollback field temporarily implemented as extra_option."""
        return int(self.mbd_get_extra_option("Rollback", "0"))

    def mbd_get_distribution_string(self, repository, distribution, rollback=None):
        dist_string = f"{distribution.base_source.codename}-{repository.identity}-{self.suite.name}"

        if rollback is None:
            return dist_string

        if rollback not in list(range(self.rollback)):
            raise Exception(f"Rollback number out of range: {rollback} ({self.rollback})")
        return f"{dist_string}-rollback{rollback}"

    def mbd_get_apt_pin(self, repository, distribution):
        return f"release n={self.mbd_get_distribution_string(repository, distribution)}, o={self.mbd_get_daemon().model.mbd_get_archive_origin()}"

    def mbd_get_apt_preferences(self, repository, distribution, prio=1):
        return f"Package: *\nPin: {self.mbd_get_apt_pin(repository, distribution)}\nPin-Priority: {prio}\n"

    def mbd_get_sort_no(self):
        """Compute number that may be used to sort suites from 'stable' (0) towards 'experimental'."""
        no = 0
        if self.uploadable:
            no += 5
        if self.migrates_to:
            no += 5
        if self.experimental:
            no += 20
        return no


class SuiteOptionInline(django.contrib.admin.TabularInline):
    model = SuiteOption
    extra = 1


class Layout(mini_buildd.models.base.Model):
    name = django.db.models.CharField(primary_key=True, max_length=100)

    suites = django.db.models.ManyToManyField(Suite, through=SuiteOption)

    # Version magic
    default_version = django.db.models.CharField(
        max_length=100, default="~%IDENTITY%%CODEVERSION%+1",
        help_text="""Version string to append to the original version for automated ports; you may use these placeholders:<br />

%IDENTITY%: Repository identity (see 'Repository').<br />
%CODEVERSION%: Numerical base distribution version (see 'Source').
""")
    mandatory_version_regex = django.db.models.CharField(
        max_length=100, default=r"~%IDENTITY%%CODEVERSION%\+[1-9]",
        help_text="Mandatory version regex; you may use the same placeholders as for 'default version'.")

    # Version magic (experimental)
    experimental_default_version = django.db.models.CharField(
        max_length=30, default="~%IDENTITY%%CODEVERSION%+0",
        help_text="Like 'default version', but for suites flagged 'experimental'.")

    experimental_mandatory_version_regex = django.db.models.CharField(
        max_length=100, default=r"~%IDENTITY%%CODEVERSION%\+0",
        help_text="Like 'mandatory version', but for suites flagged 'experimental'.")

    class Admin(mini_buildd.models.base.Model.Admin):
        fieldsets = (
            ("Basics", {"fields": ("name",)}),
            ("Version Options", {"classes": ("collapse",),
                                 "fields": ("default_version", "mandatory_version_regex",
                                            "experimental_default_version", "experimental_mandatory_version_regex")}),
            ("Extra Options", {"classes": ("collapse",),
                               "description": """
<b>Supported extra options</b>
<p><em>Meta-Distributions: META=CODENAME-SUITE[ META=CODENAME-SUITE[...</em>: Support METAs alone as distribution identifier.</p>
<p>
Meta distribution identifiers should be unique across all
repositories; usually, a layout with meta distributions should
only be used by at most one repository.
</p>
<p>
<em>Example</em>:
<kbd>Meta-Distributions: unstable=sid-unstable experimental=sid-experimental</kbd>
(see standard layout 'Debian Developer'), to allow upload/testing of
packages (to unstable,experimental,..) aimed for Debian.
</p>
""",
                               "fields": ("extra_options",)}),)
        inlines = (SuiteOptionInline,)

        @classmethod
        def mbd_meta_create_defaults(cls, msglog):
            """Create default layouts and suites."""
            stable, created = Suite.mbd_get_or_create(msglog, name="stable")
            hotfix, created = Suite.mbd_get_or_create(msglog, name="hotfix")
            testing, created = Suite.mbd_get_or_create(msglog, name="testing")
            unstable, created = Suite.mbd_get_or_create(msglog, name="unstable")
            snapshot, created = Suite.mbd_get_or_create(msglog, name="snapshot")
            experimental, created = Suite.mbd_get_or_create(msglog, name="experimental")

            for name, extra_options in list({"Default": {"stable": "Rollback: 6\n",
                                                         "hotfix": "Rollback: 4\n",
                                                         "testing": "Rollback: 3\n",
                                                         "unstable": "Rollback: 9\n",
                                                         "snapshot": "Rollback: 12\n",
                                                         "experimental": "Rollback: 6\n"},
                                             "Default (no rollbacks)": {}}.items()):
                default_layout, created = Layout.mbd_get_or_create(msglog, name=name)
                if created:
                    so_stable = SuiteOption(
                        layout=default_layout,
                        suite=stable,
                        uploadable=False,

src/mini_buildd/templates/mini_buildd/account_profile.html
{% extends "registration/base.html" %}
{% load mini_buildd_tags %}

{% block title %}Manage your profile{% endblock %}

{% block reg_content %}
	<h3>Package subscriptions</h3>

	<p>
		<em>Note:</em> You can manage package-specific subscriptions
		when viewing a source package's overview ("show").
	</p>
	<p>
		{% mbd_api "subscription" value_subscription=":" output=referer %}
	</p>
	<hr/>

	<h3>Package uploads</h3>
	<p>
		Status: <kbd class="status {{ user.uploader.get_status_display }}">{{ user.uploader|default:"ERROR: User has no uploader config. Please contact administrator." }}</kbd>
	</p>

	<p>
		<em>Note:</em> Setting a new key will <em>automatically
		deactivate your uploader profile</em>; an administrator
		needs to (verify your key and) manually re-activate you
		later.
	</p>
	{% mbd_api "setuserkey" value_key=user.uploader.key output=referer %}
{% endblock %}

src/mini_buildd/templates/mini_buildd/api.html
{% extends "mini_buildd/base.html" %}
{% load mini_buildd_tags %}

{% block page_title %}API call{% endblock %}
{% block page_sub_title %}{% mbd_api api_cmd.name %}{% endblock %}

src/mini_buildd/templates/mini_buildd/api_confirm.html
{% extends "mini_buildd/api.html" %}

{% block content %}
	<div class="api-confirm">
		<b>{{ api_cmd.name }}</b>
		{% for k, v in api_cmd.args.items %}
			{% if v %}
				{{ k }}=<b>{{ v.raw_value }}</b>
			{% endif %}
		{% endfor %}
		<form action="/mini_buildd/api" method="get">
			<div>
				<input type="hidden" name="command" value="{{ api_cmd.name }}" />
				{% for k, v in api_cmd.args.items %}
					<input type="hidden" name="{{ k }}" value="{{ v.raw_value }}" />
				{% endfor %}
				<input type="hidden" name="confirm" value="{{ api_cmd.name }}" />
				{% if referer %}
					<input type="hidden" name="output" value="referer{{ referer }}" />
				{% endif %}
				<input type="submit" value="Yes, run {{ api_cmd.name }}" title="Really run {{ api_cmd.name }}" />
			</div>
		</form>
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/api_default.html
{% extends "mini_buildd/api.html" %}
{% load mini_buildd_tags %}

{% block content %}
	<div id="mbd-api">
		<div class="box">
			<h1 class="box-caption">API call: {{ api_cmd.name }}</h1>
			<pre>{{ api_cmd.result | mbd_api_plain }}</pre>
		</div>
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/api_index.html
{% extends "mini_buildd/api.html" %}
{% load mini_buildd_tags %}

{% block page_title %}API Index{% endblock %}
{% block page_sub_title %}API usage reference{% endblock %}

{% block content %}
	<div id="mbd-api">
		<p>
			See also <kbd><b>? mini-buildd-tool --help</b></kbd> on the command line.
		</p>
		{% for name, cmd in COMMANDS.items %}
			{% if cmd.isgroup %}
				<h1>{{ cmd.name }}</h1>
				<pre>{{ cmd.doc }}</pre>
			{% else %}
				<h2>{{ cmd.name }}</h2>
				<pre>{{ cmd.doc }}</pre>
				<div style="border-style: solid; border-width: thin;">
					{% mbd_api name %}
				</div>
			{% endif %}
		{% endfor %}
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/api_list.html
{% extends "mini_buildd/api.html" %}
{% load mini_buildd_tags %}

{% block page_title %}{{ api_cmd.args.pattern.value }}{% endblock %}
{% block page_sub_title %}Source and binary package matches{% endblock %}

{% block content %}
	<div id="mbd-api_list">
		{% for repository, results in api_cmd.result.items %}
			<div class="box">
				<h1 class="box-caption">
					<a class="box-anchor"
						 title="goto repository {{ repository }}"
						 href="/mini_buildd/repositories/{{ repository }}/">Repository '{{ repository }}': {{ results|length }} packages
					</a>
				</h1>
				<table>
					<tr>
						<th>Package</th>
						<th>Type</th>
						<th>Architecture</th>
						<th>Distribution</th>
						<th>Component</th>
						<th>Version</th>
						<th>Source</th>
					</tr>
					{% for package in results %}
						<tr>
							<td>{{ package.package }}</td>
							<td>{{ package.type }}</td>
							<td>{{ package.architecture }}</td>
							<td>{{ package.distribution }}</td>
							<td>{{ package.component }}</td>
							<td>{{ package.version }}</td>
							<td>{{ package.source|urlencode }}{% mbd_api "show" value_package=package.source %}</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		{% endfor %}
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/api_show.html
{% extends "mini_buildd/api.html" %}
{% load mini_buildd_tags %}

{% block page_title %}{{ api_cmd.args.package.value }}{% endblock %}
{% block page_sub_title %}Source package{% endblock %}

{% block content %}
	<div id="mbd-api-show">
		{% for repository, codenames in api_cmd.result.items %}
			<div class="box">
				<h1 class="box-caption">
					<a class="box-anchor"
						 title="goto repository '{{ repository }}'"
						 href="/mini_buildd/repositories/{{ repository }}/">Repository '{{ repository }}'
					</a>
				</h1>

				<table>
					<tr>
						<th>Distribution</th>
						<th>Component</th>
						<th colspan="2">Version</th>
						<th>Migration</th>
						<th>Removal</th>
						<th>Rollbacks</th>
						<th colspan="2">Extras</th>
					</tr>
					{% for codename, distributions in codenames %}
						<tr>
							<td class="codename" colspan="9">{{ codename }}</td>
						</tr>
						{% for values in distributions|dictsort:"sort_no" %}
							<tr>
								<td class="distribution">{{ values.distribution }}</td>
								<td>{{ values.component }}</td>
								<td class="version">
									{% if values.sourceversion %}
										<a href="/mini_buildd/log/{{ repository }}/{{ api_cmd.args.package.value }}/{{ values.sourceversion }}/" title="Build logs">{{ values.sourceversion }}</a>
									{% endif %}
								</td>
								<td>
									{% if values.sourceversion %}
										[<a href="{{ values.dsc_path }}" title="Source package URL">dsc</a>|<a href="{{ values.dsc_path|mbd_dirname }}/" title="Browse package pool directory">pool</a>]
									{% endif %}
								</td>
								<td>
									{% if values.migrates_to %}
										{% if values.sourceversion and not values.is_migrated %}
											{% mbd_api "migrate" title="...to "|add:values.migrates_to value_package=values.source value_distribution=values.distribution value_version=values.sourceversion output=referer %}
										{% elif values.sourceversion %}
											<div title="...to {{ values.migrates_to }}"><b>Migrated</b></div>
										{% else %}
											<div title="...to {{ values.migrates_to }}">Migrates</div>
										{% endif %}
									{% endif %}
								</td>
								<td>
									{% if values.sourceversion %}
										{% mbd_api "remove" title="...from "|add:values.distribution value_package=values.source value_distribution=values.distribution value_version=values.sourceversion output=referer %}
									{% endif %}
								</td>
								<td>
									{{ values.rollbacks|length }}/{{ values.rollback }}
									<details>
										<summary>Rollbacks</summary>
										{% for rollback in values.rollbacks|dictsort:"no" %}
											<br />
											<div>
												{% mbd_api "remove" name=rollback.no title="Remove "|add:rollback.sourceversion|add:" from "|add:rollback.distribution value_package=rollback.source value_distribution=rollback.distribution value_version=rollback.sourceversion output=referer %}
												{% if not values.sourceversion %}
													{% mbd_api "migrate" name=rollback.no title="Restore rollback "|add:rollback.sourceversion|add:" from "|add:rollback.distribution value_package=rollback.source value_distribution=rollback.distribution value_version=rollback.sourceversion output=referer %}
												{% endif %}
												[<a title="Get dsc of {{ rollback.sourceversion }} from {{ rollback.distribution }}"
														href="{{ rollback.dsc_path }}">dsc</a>|<a href="/mini_buildd/log/{{ repository }}/{{ api_cmd.args.package }}/{{ rollback.sourceversion }}/" title="Build logs">logs</a>]
											</div>
										{% endfor %}
									</details>

								</td>

								<td>
									{% if values.sourceversion and values.uploadable %}
										{% mbd_api "port" name="Rebuild" title="...in "|add:values.distribution value_package=values.source value_from_distribution=values.distribution value_to_distributions=values.distribution value_version=values.sourceversion output=referer %}
									{% endif %}
								</td>
								<td>
									{% if values.sourceversion %}
										<details>
											<summary>Port Options</summary>
											{% mbd_api "port" title="Port this package version to other distribution(s)" value_package=values.source value_from_distribution=values.distribution value_version=values.sourceversion output=referer %}
										</details>
									{% endif %}
								</td>
							</tr>
						{% endfor %}
						<!-- omg. this tr is for some extra space only. fix in css -->
						<tr>
							<td colspan="8"></td>
						</tr>
					{% endfor %}
				</table>
			</div>
		{% endfor %}
	</div>

	<!-- Manage package specific subscriptions -->
	{% mbd_api "subscription" value_subscription=api_cmd.args.package.value|add:":" output=referer %}

{% endblock %}

src/mini_buildd/templates/mini_buildd/base.html
{% extends "base.html" %}
{% load mini_buildd_tags %}

{% block page_header %}
	<div class="left">
		<div class="menu-title">
			Page
		</div>
		{% if api_cmd.args.package %}
			{% with api_cmd.args.package.value as package %}
				{% mbd_api "show" title=package value_package=package %}
				<br />
				<a href="https://tracker.debian.org/pkg/{{ package|urlencode }}" title="Show {{ package }} source package in the Debian Package Tracker">Show Debian</a>
				(<a href="http://packages.qa.debian.org/common/index.html?src={{ package|urlencode }}" title="Show {{ package }} source package in the (traditional) Debian PTS">Old</a>)
				<br />
			{% endwith %}
		{% endif %}
	</div>
	<div class="center">
		<div class="title">{% block page_title %}{% endblock %}</div><div class="sub-title">{% block page_sub_title %}{% endblock %}</div>
	</div>
	<div class="right">
		{% mbd_api "show" %}
		<br />
		{% mbd_api "list" %}
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/error.html
{% extends "mini_buildd/base.html" %}
{% load mini_buildd_tags %}

{% block page_title %}Error {{ code }}{% endblock %}
{% block page_sub_title %}{{ meaning }}{% endblock %}

{% block content %}
	<div id="mbd_http_error">
		<div class="box error">
			<h1 class="box-caption error">{{ code }} {{ meaning }}</h1>
			<p>{{ description }}</p>
		</div>
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/log.html
{% extends "mini_buildd/base.html" %}
{% load mini_buildd_tags %}

{% block page_title %}Logs for: {{ repository }}/{{ package }}/{{ version }}{% endblock %}

{% block content %}
	<div id="mbd-api">
		<div class="box">
			<h1 class="box-caption">Logs for: {{ repository }}/{{ package }}/{{ version }}</h1>
			{% for key, values in logs %}
				{% if values.changes %}
					<h2 class="{{ key }}">{{ key }}</h2>
					{% ifequal key "Failed" %}
						<p>
							{% mbd_api "retry" value_package=package value_version=version value_repository=repository %}
						</p>
					{% endifequal %}
					<p>
						<a title="Browse log directory" href="/log/{{ repository }}{% ifequal key "Failed" %}/_failed{% endifequal %}/{{ package }}/{{ version }}/">Browse files</a>
						{% mbd_api "show" value_package=package %}
					</p>
					<hr/>

					<h3>Build logs</h3>
					<p>
						{% for arch, uri in values.buildlogs.items %}
							<a title="Build log for {{ arch }}" href="/log{{ uri }}">{{ arch }}</a>
						{% endfor %}
					</p>
					<hr/>

					<h3><a title="Download changes for {{ repository }}/{{ package }}/{{ version }}" href="/log{{ values.changes_path }}">Changes</a></h3>
					<pre>{{ values.changes }}</pre>
				{% endif %}
			{% endfor %}
		</div>
	</div>
{% endblock %}

src/mini_buildd/templates/mini_buildd/repository_detail.html
{% extends "mini_buildd/base.html" %}
{% load mini_buildd_tags %}

{% block page_title %}Repository {{ object.identity }}{% endblock %}
{% block page_sub_title %}Overview{% endblock %}

{% block content %}

	<div id="mbd_repository">
		{% mbd_api "getuploaders" value_repository=object.identity %}

		{% for d in object.distributions.all %}
			<div class="inner-box">
				<details>
					<summary class="header">{{ d }}</summary>
					{% for s in object.layout.suiteoption_set.all %}
						<details>
							<summary class="header">
								<span style="color: black">{{ d.base_source.codename }}-{{ object.identity }}-{{ s.suite.name }}</span>:
								<span class="emphasize-headline">{% mbd_repository_desc object d s %}</span>
								{% if s.uploadable %}
									<kbd style="font-size: 0.8em; color: purple">(U='{% mbd_repository_mandatory_version object d s %}')</kbd>
								{% endif %}
								{% if s.experimental %}
									<kbd style="font-size: 0.8em; color: red">(E)</kbd>
								{% endif %}
								<span id="mbd_dist_{{ d.base_source.codename }}_{{ s.suite.name }}_header" style="float: right">(show)</span>
								{% if s.migrates_to %}
									<kbd style="font-size: 0.8em; color: green"> =&gt; {{ s.migrates_to.suite.name }}</kbd>
								{% endif %}
							</summary>
							<ul>
								<li>APT line
									(Download:
									{% mbd_api "getkey" name="APT key" output="plain" %}
									{% mbd_api "getsourceslist" output="plain" value_suite=s.suite.name value_codename=d.base_source.codename value_with_extra_sources=False value_repository=object.identity name="deb" value_with_deb_src=False %}
									{% mbd_api "getsourceslist" output="plain" value_suite=s.suite.name value_codename=d.base_source.codename value_with_extra_sources=False value_repository=object.identity name="deb+src" value_with_deb_src=True %})
									:
									<pre class="pre-block">{% mbd_distribution_apt_line d object s %}</pre></li>
								{% if s.uploadable %}
									<li>Building with APT sources.list:<div class="pre-block"><pre>{% mbd_distribution_apt_sources_list d object s %}</pre></div></li>
									<li>Building with APT preferences:<div class="pre-block"><pre>{% mbd_distribution_apt_preferences d object s %}</pre></div></li>
								{% endif %}
								<li>Browse repository:
									<a href="/repositories/{{ object.identity }}/pool/">pool/</a>
									<a href="/repositories/{{ object.identity }}/dists/{{ d.base_source.codename }}-{{ object.identity }}-{{ s.suite.name }}/">dists/</a>
								</li>
							</ul>
						</details>
					{% endfor %}
				</details>
			</div>
		{% endfor %}
	</div>
{% endblock %}